export declare const TSCONFIG_OPTIONS: {
    alwaysStrict: undefined;
    declaration: undefined;
    esModuleInterop: undefined;
    exactOptionalPropertyTypes: undefined;
    experimentalDecorators: undefined;
    forceConsistentCasingInFileNames: undefined;
    inlineSourceMap: undefined;
    inlineSources: undefined;
    isolatedModules: undefined;
    lib: undefined;
    module: undefined;
    noEmitOnError: undefined;
    noFallthroughCasesInSwitch: undefined;
    noImplicitAny: undefined;
    noImplicitOverride: undefined;
    noImplicitReturns: undefined;
    noImplicitThis: undefined;
    noPropertyAccessFromIndexSignature: undefined;
    noUncheckedIndexedAccess: undefined;
    noUnusedLocals: undefined;
    noUnusedParameters: undefined;
    resolveJsonModule: undefined;
    skipLibCheck: undefined;
    strict: undefined;
    strictNullChecks: undefined;
    strictPropertyInitialization: undefined;
    stripInternal: undefined;
    target: undefined;
};
export declare const TSCONFIG_OPTIONS_STRICT: {
    strict: true;
    exactOptionalPropertyTypes: true;
    noFallthroughCasesInSwitch: true;
    noImplicitOverride: true;
    noImplicitReturns: true;
    noPropertyAccessFromIndexSignature: true;
    noUncheckedIndexedAccess: true;
    noUnusedLocals: true;
    noUnusedParameters: true;
    isolatedModules: true;
    esModuleInterop: true;
    skipLibCheck: true;
    forceConsistentCasingInFileNames: true;
};
